---
# this playbook runs SZWESAMP(ZWEKRING) and ZWEDELKR.jcl
- name: Remove ZWEKRING.jcl or ZWEKRING.raw.jcl if exists
  raw: >-
    rm -f "{{ work_dir_remote }}/ZWEKRING.raw.jcl";
    rm -f "{{ work_dir_remote }}/ZWEKRING.jcl"

# ============================================================================
# Prepare ZWEDELKR.jcl
- name: Prepare ZWEDELKR.jcl
  template:
    src: ZWEDELKR.jcl.j2
    dest: "{{ work_dir_local }}/{{ inventory_hostname }}/ZWEDELKR.jcl"
    newline_sequence: '\n'
    mode: 0700
  delegate_to: localhost

- name: Upload ZWEDELKR.jcl to server
  include_role:
    name: common
    tasks_from: upload_file
  vars:
    filename_to_upload: "ZWEDELKR.jcl"
    file_upload_method: scp
    file_upload_hashcheck: false

- name: Check ZWEDELKR.jcl content
  raw: cat "{{ work_dir_remote }}/ZWEDELKR.jcl"

# Run ZWEDELKR.jcl
- name: Run ZWEDELKR.jcl to uninstall previous installation
  include_role:
    name: zos
    tasks_from: run_jcl
  vars:
    jcl_filename: "{{ work_dir_remote }}/ZWEDELKR.jcl"

# ============================================================================
# Prepare ZWEKRING.jcl
- name: Copy SZWESAMP(ZWEKRING) to USS
  raw: cp "//'{{ zowe_dataset_prefix }}.SZWESAMP(ZWEKRING)'" "{{ work_dir_remote }}/ZWEKRING.raw.jcl"

# FIXME: Option 2 is enabled by default
- name: Update ZWEKRING.jcl with configurations
  raw: >-
    cat "{{ work_dir_remote }}/ZWEKRING.raw.jcl" | \
    sed -e "s+PRODUCT=RACF+PRODUCT={{ zos_security_system }}+" | \
    sed -e "s+ZOWEUSER=ZWESVUSR+ZOWEUSER={{ zowe_runtime_user }}+" | \
    sed -e "s+LABEL=''+LABEL='{{ zowe_safkeyring_certificate_label }}'+" | \
    sed -e "s+ROOTZFCA=+ROOTZFCA='{{ zowe_safkeyring_zosmf_root_ca }}'+" | \
    sed -e "s+DOMAIN=localhost+DOMAIN={{ zowe_external_domain_name }}+" \
    > "{{ work_dir_remote }}/ZWEKRING.jcl"

- name: Check ZWEKRING.jcl changes
  raw: cat "{{ work_dir_remote }}/ZWEKRING.jcl"

- name: Run ZWEKRING.jcl
  import_role:
    name: zos
    tasks_from: run_jcl
  vars:
    jcl_filename: "{{ work_dir_remote }}/ZWEKRING.jcl"

- name: Remove ZWEKRING.jcl or ZWEKRING.raw.jcl if exists
  raw: >-
    rm -f "{{ work_dir_remote }}/ZWEKRING.raw.jcl";
    rm -f "{{ work_dir_remote }}/ZWEKRING.jcl"
